site:
  title: Deploying Red Hat Edge Manager and Managing Edge Devices
  start_page: rhde-rhem-devices::index.adoc

content:
  sources:
  - url: ./
  - url: https://github.com/RedHatQuickCourses/rhde-rhem-samples.git

asciidoc:
  attributes:
    page-pagination: true

ui:
  bundle:
    url: ./ui-bundle/ui-bundle.zip
  supplemental_files: ./supplemental-ui
